# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 737)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_data = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tab_data.setObjectName("tab_data")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image_view = QtWidgets.QLabel(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_view.sizePolicy().hasHeightForWidth())
        self.image_view.setSizePolicy(sizePolicy)
        self.image_view.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 16px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 0px;                /* Khoảng cách nội dung */\n"
"    border: 1px solid gray;      /* Viền 2px màu đen */\n"
"    border-radius: 5px;          /* Bo góc viền 5px */\n"
"}\n"
"")
        self.image_view.setText("")
        self.image_view.setObjectName("image_view")
        self.verticalLayout_3.addWidget(self.image_view)
        self.status = QtWidgets.QLabel(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 14px;             /* Cỡ chữ */\n"
"    font-weight: Regular;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 5px;                /* Khoảng cách nội dung */\n"
"    border: 1px 1x solid gray;      /* Viền 2px màu xám */\n"
"    border-radius: 5px;          /* Bo góc viền 5px */\n"
"}")
        self.status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status.setObjectName("status")
        self.verticalLayout_3.addWidget(self.status)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 3, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 50)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(48, 100, 255); /* Màu nền xanh lá */\n"
"    color: white;                /* Chữ màu trắng */\n"
"    font-size: 14px;             /* Cỡ chữ 14px */\n"
"    padding: 10px 20px;          /* Padding trên/dưới 10px, trái/phải 20px */\n"
"    border-radius: 5px;          /* Bo tròn góc 5px */\n"
"    border: none;                /* Loại bỏ viền */\n"
"    cursor: pointer;             /* Con trỏ chuột thành dạng bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgba(0, 0, 127,0.5);    /* Màu nền thay đổi khi di chuột vào */\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(48, 100, 255); /* Màu nền xanh lá */\n"
"    color: white;                /* Chữ màu trắng */\n"
"    font-size: 14px;             /* Cỡ chữ 14px */\n"
"    padding: 10px 20px;          /* Padding trên/dưới 10px, trái/phải 20px */\n"
"    border-radius: 5px;          /* Bo tròn góc 5px */\n"
"    border: none;                /* Loại bỏ viền */\n"
"    cursor: pointer;             /* Con trỏ chuột thành dạng bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgba(0, 0, 127,0.5);    /* Màu nền thay đổi khi di chuột vào */\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.formFrame = QtWidgets.QFrame(parent=self.tab)
        self.formFrame.setObjectName("formFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.formFrame)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(-1, 46, -1, 58)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 14px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 10px;                /* Khoảng cách nội dung */\n"
"    /*border: 1px solid gray;      /* Viền 2px màu đen */\n"
"    /*border-radius: 5px;          /* Bo góc viền 5px */\n"
"    border-top: none;   /* Viền trên */\n"
"    border-right: none;           /* Không có viền phải */\n"
"    border-bottom:1px solid gray;         /* Không có viền dưới */\n"
"    border-left: none;            /* Không có viền trái */\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 14px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 10px;                /* Khoảng cách nội dung */\n"
"   /* border: 1px solid gray;      /* Viền 2px màu đen */\n"
"   /* border-radius: 5px;          /* Bo góc viền 5px */\n"
"    border-top: none;   /* Viền trên */\n"
"    border-right: none;           /* Không có viền phải */\n"
"    border-bottom:1px solid gray;         /* Không có viền dưới */\n"
"    border-left: none;            /* Không có viền trái */\n"
"}")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 14px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 10px;                /* Khoảng cách nội dung */\n"
"   /* border: 1px solid gray;      /* Viền 2px màu đen */\n"
"   /* border-radius: 5px;          /* Bo góc viền 5px */\n"
"    border-top: none;   /* Viền trên */\n"
"    border-right: none;           /* Không có viền phải */\n"
"    border-bottom:1px solid gray;         /* Không có viền dưới */\n"
"    border-left: none;            /* Không có viền trái */\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 14px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 10px;                /* Khoảng cách nội dung */\n"
"   /* border: 1px solid gray;      /* Viền 2px màu đen */\n"
"   /* border-radius: 5px;          /* Bo góc viền 5px */\n"
"    border-top: none;   /* Viền trên */\n"
"    border-right: none;           /* Không có viền phải */\n"
"    border-bottom:1px solid gray;         /* Không có viền dưới */\n"
"    border-left: none;            /* Không có viền trái */\n"
"}")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.formFrame)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 14px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 10px;                /* Khoảng cách nội dung */\n"
"   /* border: 1px solid gray;      /* Viền 2px màu đen */\n"
"   /* border-radius: 5px;          /* Bo góc viền 5px */\n"
"    border-top: none;   /* Viền trên */\n"
"    border-right: none;           /* Không có viền phải */\n"
"    border-bottom:1px solid gray;         /* Không có viền dưới */\n"
"    border-left: none;            /* Không có viền trái */\n"
"}")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 14px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 10px;                /* Khoảng cách nội dung */\n"
"   /* border: 1px solid gray;      /* Viền 2px màu đen */\n"
"   /* border-radius: 5px;          /* Bo góc viền 5px */\n"
"    border-top: none;   /* Viền trên */\n"
"    border-right: none;           /* Không có viền phải */\n"
"    border-bottom:1px solid gray;         /* Không có viền dưới */\n"
"    border-left: none;            /* Không có viền trái */\n"
"}")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.formFrame, 0, 0, 1, 1)
        self.tab_data.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.change_model_file = QtWidgets.QPushButton(parent=self.tab_3)
        self.change_model_file.setGeometry(QtCore.QRect(20, 60, 171, 61))
        self.change_model_file.setObjectName("change_model_file")
        self.change_ai_model = QtWidgets.QPushButton(parent=self.tab_3)
        self.change_ai_model.setGeometry(QtCore.QRect(20, 140, 171, 61))
        self.change_ai_model.setObjectName("change_ai_model")
        self.change_feature_file = QtWidgets.QPushButton(parent=self.tab_3)
        self.change_feature_file.setGeometry(QtCore.QRect(20, 220, 171, 61))
        self.change_feature_file.setObjectName("change_feature_file")
        self.model_ver = QtWidgets.QLabel(parent=self.tab_3)
        self.model_ver.setGeometry(QtCore.QRect(220, 67, 531, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_ver.sizePolicy().hasHeightForWidth())
        self.model_ver.setSizePolicy(sizePolicy)
        self.model_ver.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 14px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 10px;                /* Khoảng cách nội dung */\n"
"    /*border: 1px solid gray;      /* Viền 2px màu đen */\n"
"    /*border-radius: 5px;          /* Bo góc viền 5px */\n"
"    border-top: none;   /* Viền trên */\n"
"    border-right: none;           /* Không có viền phải */\n"
"    border-bottom:1px solid gray;         /* Không có viền dưới */\n"
"    border-left: none;            /* Không có viền trái */\n"
"}")
        self.model_ver.setText("")
        self.model_ver.setObjectName("model_ver")
        self.ai_ver = QtWidgets.QLabel(parent=self.tab_3)
        self.ai_ver.setGeometry(QtCore.QRect(220, 150, 531, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ai_ver.sizePolicy().hasHeightForWidth())
        self.ai_ver.setSizePolicy(sizePolicy)
        self.ai_ver.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 14px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 10px;                /* Khoảng cách nội dung */\n"
"    /*border: 1px solid gray;      /* Viền 2px màu đen */\n"
"    /*border-radius: 5px;          /* Bo góc viền 5px */\n"
"    border-top: none;   /* Viền trên */\n"
"    border-right: none;           /* Không có viền phải */\n"
"    border-bottom:1px solid gray;         /* Không có viền dưới */\n"
"    border-left: none;            /* Không có viền trái */\n"
"}")
        self.ai_ver.setText("")
        self.ai_ver.setObjectName("ai_ver")
        self.feature_ver = QtWidgets.QLabel(parent=self.tab_3)
        self.feature_ver.setGeometry(QtCore.QRect(220, 230, 531, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feature_ver.sizePolicy().hasHeightForWidth())
        self.feature_ver.setSizePolicy(sizePolicy)
        self.feature_ver.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 14px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 10px;                /* Khoảng cách nội dung */\n"
"    /*border: 1px solid gray;      /* Viền 2px màu đen */\n"
"    /*border-radius: 5px;          /* Bo góc viền 5px */\n"
"    border-top: none;   /* Viền trên */\n"
"    border-right: none;           /* Không có viền phải */\n"
"    border-bottom:1px solid gray;         /* Không có viền dưới */\n"
"    border-left: none;            /* Không có viền trái */\n"
"}")
        self.feature_ver.setText("")
        self.feature_ver.setObjectName("feature_ver")
        self.tab_data.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formFrame_2 = QtWidgets.QFrame(parent=self.tab_2)
        self.formFrame_2.setObjectName("formFrame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.formFrame_2)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(-1, 46, -1, 58)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ex = QtWidgets.QLabel(parent=self.formFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ex.sizePolicy().hasHeightForWidth())
        self.ex.setSizePolicy(sizePolicy)
        self.ex.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 14px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 10px;                /* Khoảng cách nội dung */\n"
"    /*border: 1px solid gray;      /* Viền 2px màu đen */\n"
"    /*border-radius: 5px;          /* Bo góc viền 5px */\n"
"    border-top: none;   /* Viền trên */\n"
"    border-right: none;           /* Không có viền phải */\n"
"    border-bottom:1px solid gray;         /* Không có viền dưới */\n"
"    border-left: none;            /* Không có viền trái */\n"
"}")
        self.ex.setObjectName("ex")
        self.gridLayout_3.addWidget(self.ex, 0, 0, 1, 1)
        self.exposure_txt = QtWidgets.QLabel(parent=self.formFrame_2)
        self.exposure_txt.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 14px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 10px;                /* Khoảng cách nội dung */\n"
"   /* border: 1px solid gray;      /* Viền 2px màu đen */\n"
"   /* border-radius: 5px;          /* Bo góc viền 5px */\n"
"    border-top: none;   /* Viền trên */\n"
"    border-right: none;           /* Không có viền phải */\n"
"    border-bottom:1px solid gray;         /* Không có viền dưới */\n"
"    border-left: none;            /* Không có viền trái */\n"
"}")
        self.exposure_txt.setObjectName("exposure_txt")
        self.gridLayout_3.addWidget(self.exposure_txt, 0, 2, 1, 1)
        self.exposure_slider = QtWidgets.QSlider(parent=self.formFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposure_slider.sizePolicy().hasHeightForWidth())
        self.exposure_slider.setSizePolicy(sizePolicy)
        self.exposure_slider.setBaseSize(QtCore.QSize(0, 0))
        self.exposure_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.exposure_slider.setObjectName("exposure_slider")
        self.gridLayout_3.addWidget(self.exposure_slider, 1, 0, 1, 3)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.formFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 2, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.formFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 2, 1, 1, 2)
        self.gridLayout_4.addWidget(self.formFrame_2, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.image_view_2 = QtWidgets.QLabel(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_view_2.sizePolicy().hasHeightForWidth())
        self.image_view_2.setSizePolicy(sizePolicy)
        self.image_view_2.setStyleSheet("QLabel {\n"
"    color: #333;                 /* Màu chữ */\n"
"    font-size: 16px;             /* Cỡ chữ */\n"
"    font-weight: bold;           /* Đậm chữ */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    padding: 0px;                /* Khoảng cách nội dung */\n"
"    border: 1px solid gray;      /* Viền 2px màu đen */\n"
"    border-radius: 5px;          /* Bo góc viền 5px */\n"
"}\n"
"")
        self.image_view_2.setText("")
        self.image_view_2.setObjectName("image_view_2")
        self.verticalLayout_6.addWidget(self.image_view_2)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 1, 2, 1)
        self.verticalFrame_5 = QtWidgets.QFrame(parent=self.tab_2)
        self.verticalFrame_5.setObjectName("verticalFrame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 50)
        self.verticalLayout_7.setSpacing(9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.verticalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_7.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.verticalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_7.addWidget(self.pushButton_8)
        self.gridLayout_4.addWidget(self.verticalFrame_5, 1, 0, 1, 1)
        self.tab_data.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tab_data)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_tab_testing = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_tab_testing.sizePolicy().hasHeightForWidth())
        self.btn_tab_testing.setSizePolicy(sizePolicy)
        self.btn_tab_testing.setStyleSheet("QPushButton {\n"
"    background-color: rgb(48, 100, 255); /* Màu nền xanh lá */\n"
"    color: white;                /* Chữ màu trắng */\n"
"    font-size: 14px;             /* Cỡ chữ 14px */\n"
"    padding: 10px 20px;          /* Padding trên/dưới 10px, trái/phải 20px */\n"
"    border-radius: 5px;          /* Bo tròn góc 5px */\n"
"    border: none;                /* Loại bỏ viền */\n"
"    cursor: pointer;             /* Con trỏ chuột thành dạng bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgba(0, 0, 127,0.5);    /* Màu nền thay đổi khi di chuột vào */\n"
"}\n"
"")
        self.btn_tab_testing.setObjectName("btn_tab_testing")
        self.horizontalLayout.addWidget(self.btn_tab_testing)
        self.btn_tab_data = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.btn_tab_data.sizePolicy().hasHeightForWidth())
        self.btn_tab_data.setSizePolicy(sizePolicy)
        self.btn_tab_data.setStyleSheet("QPushButton {\n"
"    background-color: rgb(48, 100, 255); /* Màu nền xanh lá */\n"
"    color: white;                /* Chữ màu trắng */\n"
"    font-size: 14px;             /* Cỡ chữ 14px */\n"
"    padding: 10px 20px;          /* Padding trên/dưới 10px, trái/phải 20px */\n"
"    border-radius: 5px;          /* Bo tròn góc 5px */\n"
"    border: none;                /* Loại bỏ viền */\n"
"    cursor: pointer;             /* Con trỏ chuột thành dạng bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgba(0, 0, 127,0.5);    /* Màu nền thay đổi khi di chuột vào */\n"
"}\n"
"")
        self.btn_tab_data.setObjectName("btn_tab_data")
        self.horizontalLayout.addWidget(self.btn_tab_data)
        self.btn_tab_setting = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_tab_setting.sizePolicy().hasHeightForWidth())
        self.btn_tab_setting.setSizePolicy(sizePolicy)
        self.btn_tab_setting.setStyleSheet("QPushButton {\n"
"    background-color: rgb(48, 100, 255); /* Màu nền xanh lá */\n"
"    color: white;                /* Chữ màu trắng */\n"
"    font-size: 14px;             /* Cỡ chữ 14px */\n"
"    padding: 10px 20px;          /* Padding trên/dưới 10px, trái/phải 20px */\n"
"    border-radius: 5px;          /* Bo tròn góc 5px */\n"
"    border: none;                /* Loại bỏ viền */\n"
"    cursor: pointer;             /* Con trỏ chuột thành dạng bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgba(0, 0, 127,0.5);    /* Màu nền thay đổi khi di chuột vào */\n"
"}\n"
"")
        self.btn_tab_setting.setObjectName("btn_tab_setting")
        self.horizontalLayout.addWidget(self.btn_tab_setting)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1047, 26))
        self.menubar.setObjectName("menubar")
        self.menud = QtWidgets.QMenu(parent=self.menubar)
        self.menud.setObjectName("menud")
        self.menug = QtWidgets.QMenu(parent=self.menubar)
        self.menug.setObjectName("menug")
        self.menuTrinhThuan = QtWidgets.QMenu(parent=self.menug)
        self.menuTrinhThuan.setObjectName("menuTrinhThuan")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionopen_file = QtGui.QAction(parent=MainWindow)
        self.actionopen_file.setObjectName("actionopen_file")
        self.actionTS_part = QtGui.QAction(parent=MainWindow)
        self.actionTS_part.setObjectName("actionTS_part")
        self.menud.addSeparator()
        self.menud.addAction(self.actionopen_file)
        self.menuTrinhThuan.addAction(self.actionTS_part)
        self.menug.addSeparator()
        self.menug.addSeparator()
        self.menug.addAction(self.menuTrinhThuan.menuAction())
        self.menubar.addAction(self.menud.menuAction())
        self.menubar.addAction(self.menug.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_data.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.status.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_4.setText(_translate("MainWindow", "Start"))
        self.pushButton_5.setText(_translate("MainWindow", "Stop"))
        self.label_2.setText(_translate("MainWindow", "Result:"))
        self.label_6.setText(_translate("MainWindow", "Fail rate:"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "Test Time:"))
        self.tab_data.setTabText(self.tab_data.indexOf(self.tab), _translate("MainWindow", "Testing"))
        self.change_model_file.setText(_translate("MainWindow", "Model file"))
        self.change_ai_model.setText(_translate("MainWindow", "AI model"))
        self.change_feature_file.setText(_translate("MainWindow", "Feature file"))
        self.tab_data.setTabText(self.tab_data.indexOf(self.tab_3), _translate("MainWindow", "Data"))
        self.ex.setText(_translate("MainWindow", "Exposure:"))
        self.exposure_txt.setText(_translate("MainWindow", "value"))
        self.pushButton_9.setText(_translate("MainWindow", "Get "))
        self.pushButton_10.setText(_translate("MainWindow", "Set value"))
        self.pushButton_7.setText(_translate("MainWindow", "Manual Test"))
        self.pushButton_8.setText(_translate("MainWindow", "Stop"))
        self.tab_data.setTabText(self.tab_data.indexOf(self.tab_2), _translate("MainWindow", "Setting"))
        self.btn_tab_testing.setText(_translate("MainWindow", "Auto Test"))
        self.btn_tab_data.setText(_translate("MainWindow", "    Data   "))
        self.btn_tab_setting.setText(_translate("MainWindow", "  Setting  "))
        self.label.setText(_translate("MainWindow", "Created by TrinhThuan"))
        self.menud.setTitle(_translate("MainWindow", "File"))
        self.menug.setTitle(_translate("MainWindow", "About us"))
        self.menuTrinhThuan.setTitle(_translate("MainWindow", "TrinhThuan"))
        self.actionopen_file.setText(_translate("MainWindow", "open file"))
        self.actionTS_part.setText(_translate("MainWindow", "TS part"))
